global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - "/etc/prometheus/rules/*.rules"

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus/
    scrape_interval: 5s
    static_configs:
      - targets: ['54.197.203.15:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
